begin;
select no_plan();
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values
('33333333-3333-4333-8333-333333333333','authenticated','authenticated','ledger-owner@example.test','{}','{}',now(),now()),
('44444444-4444-4444-8444-444444444444','authenticated','authenticated','ledger-member@example.test','{}','{}',now(),now()),
('55555555-5555-4555-8555-555555555555','authenticated','authenticated','ledger-outsider@example.test','{}','{}',now(),now());
create temp table ledger_state(f uuid,a uuid,income uuid,expense uuid,t uuid,member_t uuid);
grant all on ledger_state to authenticated;
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',true);
set local role authenticated;
insert into ledger_state(f) select (public.create_family('Ledger test','INR','Asia/Kolkata',1::smallint,2026::smallint,gen_random_uuid())->>'id')::uuid;
update ledger_state set a=(public.create_account(f,'Cash','CASH','2024-01-01','10000','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')->>'id')::uuid;
select is((public.create_account((select f from ledger_state),'Cash','CASH','2024-01-01','10000','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')->>'id')::uuid,(select a from ledger_state),'account retries are idempotent');
select throws_ok(format('select public.create_account(%L,'' cash '',''CASH'',''2024-01-01'',''0'',gen_random_uuid())',(select f from ledger_state)),'23505',null,'duplicate account names are normalized');
update ledger_state set income=(select id from public.categories where family_id=f and type='INCOME' order by sort_order limit 1),expense=(select id from public.categories where family_id=f and type='EXPENSE' order by sort_order limit 1);
select is(public.monthly_report((select f from ledger_state),2024,2)->>'income_minor','0','empty month income is zero');
select ok(public.monthly_report((select f from ledger_state),2024,2)->>'savings_rate' is null,'empty month ratio is null');
update ledger_state set t=(public.save_transaction(f,null,null,'INCOME','2024-02-01','100000',a,income,'Income','','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb')->>'id')::uuid;
select is((public.save_transaction(f,null,null,'INCOME','2024-02-01','100000',a,income,'Income','','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb')->>'id')::uuid,t,'transaction retries return one record') from ledger_state;
select throws_ok(format('select public.save_transaction(%L,null,null,''INCOME'',''2024-02-01'',''999'',%L,%L,''Income'','''',''bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'')',f,a,income),'P0001','IDEMPOTENCY_CONFLICT','reusing key for another amount fails') from ledger_state;
select public.save_transaction(f,null,null,'EXPENSE','2024-02-29','25000',a,expense,'Leap day','',gen_random_uuid()) from ledger_state;
select public.save_transaction(f,null,null,'EXPENSE','2024-03-01','999',a,expense,'Next month','',gen_random_uuid()) from ledger_state;
select is(public.monthly_report(f,2024,2)->>'income_minor','100000','includes first day income') from ledger_state;
select is(public.monthly_report(f,2024,2)->>'expense_minor','25000','includes leap day but excludes next month') from ledger_state;
select is(public.monthly_report(f,2024,2)->>'net_minor','75000','net matches independent control') from ledger_state;
select is((public.monthly_report(f,2024,2)->>'savings_rate')::numeric,75::numeric,'savings rate matches control') from ledger_state;
select is((public.list_accounts(f)->0->>'balance_minor')::bigint,84001::bigint,'balance includes opening plus all non-deleted transactions') from ledger_state;
select is(public.monthly_report(f,2024,3)->>'net_minor','-999','expense-only month has negative net') from ledger_state;
select ok(public.monthly_report(f,2024,3)->>'expense_to_income' is null,'expense-only ratio is null') from ledger_state;
select throws_ok(format('select public.save_transaction(%L,null,null,''EXPENSE'',''2024-02-01'',''100'',%L,%L,'''','''',gen_random_uuid())',f,a,income),'P0001','CATEGORY_INVALID','category type must match') from ledger_state;
select throws_ok(format('select public.save_transaction(%L,null,null,''INCOME'',''2023-12-31'',''100'',%L,%L,'''','''',gen_random_uuid())',f,a,income),'P0001','ACCOUNT_INVALID_OR_DATE_BEFORE_OPENING','cannot predate account opening') from ledger_state;
select throws_ok(format('select public.save_transaction(%L,null,null,''INCOME'',''2024-02-01'',''0'',%L,%L,'''','''',gen_random_uuid())',f,a,income),'P0001','VALIDATION_FAILED','zero amounts rejected') from ledger_state;
select public.save_transaction(f,t,1,'INCOME','2024-02-01','110000',a,income,'Updated','',gen_random_uuid()) from ledger_state;
select throws_ok(format('select public.save_transaction(%L,%L,1,''INCOME'',''2024-02-01'',''110000'',%L,%L,''Stale'','''',gen_random_uuid())',f,t,a,income),'P0001','VERSION_CONFLICT','stale edits rejected') from ledger_state;
select public.set_transaction_deleted(f,t,2,true,gen_random_uuid()) from ledger_state;
select is(public.monthly_report(f,2024,2)->>'income_minor','0','soft-deleted row excluded from totals') from ledger_state;
select is((select count(*) from public.transactions where deleted_at is not null),1::bigint,'deleted record is retained') ;
select public.set_transaction_deleted(f,t,3,false,gen_random_uuid()) from ledger_state;
select is(public.monthly_report(f,2024,2)->>'income_minor','110000','restoration restores totals') from ledger_state;
reset role;
insert into public.family_members(family_id,user_id,role,status) select f,'44444444-4444-4444-8444-444444444444','MEMBER','PENDING' from ledger_state;
select set_config('request.jwt.claim.sub','44444444-4444-4444-8444-444444444444',true);
set local role authenticated;
select throws_ok(format('select public.monthly_report(%L,2024,2)',f),'P0001','FORBIDDEN','pending member cannot report') from ledger_state;
select is((select count(*) from public.transactions),0::bigint,'pending member cannot read rows');
reset role;
update public.family_members set status='ACTIVE' where user_id='44444444-4444-4444-8444-444444444444';
set local role authenticated;
select throws_ok(format('select public.save_transaction(%L,%L,4,''INCOME'',''2024-02-01'',''100'',%L,%L,'''','''',gen_random_uuid())',f,t,a,income),'P0001','FORBIDDEN','member cannot edit Owner transaction') from ledger_state;
select throws_ok(format('select public.create_account(%L,''Member bank'',''CASH'',''2024-01-01'',''0'',gen_random_uuid())',f),'P0001','FORBIDDEN','member cannot create household accounts') from ledger_state;
update ledger_state set member_t=(public.save_transaction(f,null,null,'EXPENSE','2024-02-10','100',a,expense,'Member entry','',gen_random_uuid())->>'id')::uuid;
select lives_ok(format('select public.save_transaction(%L,%L,1,''EXPENSE'',''2024-02-10'',''200'',%L,%L,''Member edit'','''',gen_random_uuid())',f,member_t,a,expense),'member edits own transaction') from ledger_state;
reset role;
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',true);
set local role authenticated;
select lives_ok(format('select public.save_transaction(%L,%L,2,''EXPENSE'',''2024-02-10'',''300'',%L,%L,''Owner edit'','''',gen_random_uuid())',f,member_t,a,expense),'Owner edits Member transaction') from ledger_state;
select public.remove_family_member(f,'44444444-4444-4444-8444-444444444444',gen_random_uuid()) from ledger_state;
reset role;
select set_config('request.jwt.claim.sub','44444444-4444-4444-8444-444444444444',true);
set local role authenticated;
select throws_ok(format('select public.list_accounts(%L)',f),'P0001','FORBIDDEN','removed member immediately loses access') from ledger_state;
reset role;
select set_config('request.jwt.claim.sub','55555555-5555-4555-8555-555555555555',true);
set local role authenticated;
select throws_ok(format('select public.list_transactions(%L)',f),'P0001','FORBIDDEN','wrong-family user cannot list transactions') from ledger_state;
select throws_ok(format('select public.monthly_report(%L,2024,2)',f),'P0001','FORBIDDEN','wrong-family user cannot report') from ledger_state;
reset role;
-- Scale fixture stays inside this rolled-back transaction.
insert into public.transactions(family_id,type,local_date,amount_minor,account_id,category_id,created_by,updated_by)
select f,'EXPENSE','2025-01-01',1,a,expense,'33333333-3333-4333-8333-333333333333','33333333-3333-4333-8333-333333333333' from ledger_state cross join generate_series(1,8100);
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',true);
set local role authenticated;
select is(public.monthly_report(f,2025,1)->>'expense_minor','8100','reports include all 8100 rows') from ledger_state;
select is(jsonb_array_length(public.list_transactions(f)),30,'default page bounded to 30') from ledger_state;
select is(jsonb_array_length(public.list_transactions(f,p_limit=>9999)),100,'oversized page capped at 100') from ledger_state;
select is(jsonb_array_length(public.list_transactions(f,p_type=>'INCOME')),1,'type filter works') from ledger_state;
select is(jsonb_array_length(public.list_transactions(f,p_member_id=>'44444444-4444-4444-8444-444444444444')),1,'member filter works') from ledger_state;
select is(jsonb_array_length(public.list_transactions(f,p_start=>'2024-03-01',p_end=>'2024-04-01')),1,'exclusive date range works') from ledger_state;
select ok(not exists(select 1 from jsonb_array_elements(public.list_transactions(f)) first_page join jsonb_array_elements(public.list_transactions(f,p_cursor_date=>(public.list_transactions(f)->29->>'local_date')::date,p_cursor_id=>(public.list_transactions(f)->29->>'id')::uuid)) second_page on first_page->>'id'=second_page->>'id'),'keyset pages do not overlap on tied dates') from ledger_state;
select throws_ok(format('select public.save_transaction(%L,null,null,''INCOME'',''2024-02-01'',''100'',''aaaaaaaa-1111-4111-8111-111111111111'',%L,'''','''',gen_random_uuid())',f,income),'P0001','ACCOUNT_INVALID_OR_DATE_BEFORE_OPENING','unknown or foreign account rejected') from ledger_state;
reset role;
update public.categories set archived_at=now() where id=(select income from ledger_state);
set local role authenticated;
select throws_ok(format('select public.save_transaction(%L,null,null,''INCOME'',''2024-02-01'',''100'',%L,%L,'''','''',gen_random_uuid())',f,a,income),'P0001','CATEGORY_INVALID','archived category rejected') from ledger_state;
reset role;
update public.family_members set status='ACTIVE',role='VIEWER' where user_id='44444444-4444-4444-8444-444444444444';
select set_config('request.jwt.claim.sub','44444444-4444-4444-8444-444444444444',true);
set local role authenticated;
select lives_ok(format('select public.monthly_report(%L,2024,2)',f),'Viewer can read report') from ledger_state;
select throws_ok(format('select public.save_transaction(%L,null,null,''EXPENSE'',''2024-02-01'',''100'',%L,%L,'''','''',gen_random_uuid())',f,a,expense),'P0001','FORBIDDEN','Viewer cannot write transactions') from ledger_state;
reset role;
set local role anon;
select throws_ok('select public.monthly_report(''00000000-0000-4000-8000-000000000000'',2024,2)','42501',null,'anonymous cannot execute financial reports');
reset role;
select * from finish();
rollback;
