import { useState } from 'react';
import { Alert, View } from 'react-native';
import { router } from 'expo-router';
import * as Crypto from 'expo-crypto';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { decimalMoney, formatMoney, parseMoney, isLocalDate, localToday } from '@family-ledger/domain';
import { Screen } from '@/components/ui/screen';
import { Card } from '@/components/ui/card';
import { AppText } from '@/components/ui/app-text';
import { AppField } from '@/components/ui/app-field';
import { AppButton } from '@/components/ui/app-button';
import { Choice } from '@/components/ui/choice';
import { Notice } from '@/components/ui/notice';
import { QueryFeedback } from '@/components/ui/query-feedback';
import { listAccounts, listAccountsForManagement, rpc, type Account } from '@/infrastructure/supabase/ledger';
import { useActiveFamily } from '@/providers/active-family-provider';

const accountTypes = ['CASH','BANK','SAVINGS','CURRENT','CREDIT_CARD','WALLET','EWALLET','INVESTMENT','LOAN','OTHER'];
function sum(accounts: Account[], field: 'beginning_balance_minor' | 'balance_minor' | 'total_deposits_minor' | 'total_withdrawals_minor' | 'total_adjustments_minor') { return accounts.reduce((total, account) => total + BigInt(account[field] ?? '0'), 0n).toString(); }
function checkedStatus(account: Account, today: string) {
  if (!account.last_checked_date || account.actual_balance_minor === null || account.actual_balance_minor === undefined) return 'Never checked';
  if (BigInt(account.actual_balance_minor) !== BigInt(account.balance_minor)) return 'Difference found';
  const threshold = new Date(`${today}T00:00:00Z`); threshold.setUTCDate(threshold.getUTCDate() - 30);
  return account.last_checked_date < threshold.toISOString().slice(0, 10) ? 'Stale' : 'Reconciled';
}

export default function AccountsScreen() {
  const { activeFamily: family } = useActiveFamily(); const client = useQueryClient(); const canManage = family?.role === 'OWNER' || family?.role === 'ADMIN'; const today = localToday(family?.timezone);
  const query = useQuery({ queryKey: ['accounts-screen', family?.id, canManage], queryFn: () => canManage ? listAccountsForManagement(family!.id) : listAccounts(family!.id), enabled: !!family });
  const [name, setName] = useState(''); const [type, setType] = useState('CASH'); const [date, setDate] = useState(today); const [institution, setInstitution] = useState(''); const [sortOrder, setSortOrder] = useState('0'); const [creditPositive, setCreditPositive] = useState(false);
  const [balance, setBalance] = useState('0'); const [key, setKey] = useState(Crypto.randomUUID); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [reconcileAccountId, setReconcileAccountId] = useState<string | null>(null); const [actualBalance, setActualBalance] = useState(''); const [checkedDate, setCheckedDate] = useState(today);
  const [editingAccountId, setEditingAccountId] = useState<string | null>(null); const [editingName, setEditingName] = useState(''); const [editingType, setEditingType] = useState('CASH'); const [editingInstitution, setEditingInstitution] = useState(''); const [editingSortOrder, setEditingSortOrder] = useState('0'); const [editingCreditPositive, setEditingCreditPositive] = useState(false);
  const [transferOpen, setTransferOpen] = useState(false); const [transferFrom, setTransferFrom] = useState(''); const [transferTo, setTransferTo] = useState(''); const [transferAmount, setTransferAmount] = useState(''); const [transferDate, setTransferDate] = useState(today); const [transferDescription, setTransferDescription] = useState('Account transfer'); const [transferRemarks, setTransferRemarks] = useState('');
  const active = (query.data ?? []).filter((account) => !account.archived_at); const archived = (query.data ?? []).filter((account) => !!account.archived_at);
  async function refresh() { await Promise.all([client.invalidateQueries({ queryKey: ['accounts', family?.id] }), client.invalidateQueries({ queryKey: ['accounts-screen', family?.id] })]); }
  async function save() {
    if (!family || busy) return; setBusy(true); setError('');
    try { if (!name.trim() || name.trim().length > 80 || !isLocalDate(date) || !/^\d+$/.test(sortOrder)) throw new Error('Enter a name, valid opening date and non-negative display order.'); await rpc('create_account_extended', { p_family_id: family.id, p_name: name.trim(), p_account_type: type, p_opening_date: date, p_balance_minor: parseMoney(balance, true), p_institution: institution, p_sort_order: Number(sortOrder), p_display_credit_as_positive: creditPositive, p_idempotency_key: key }); setName(''); setInstitution(''); setSortOrder('0'); setCreditPositive(false); setBalance('0'); setKey(Crypto.randomUUID()); await refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message.replace('ACCOUNT_ALREADY_EXISTS', 'An active account with this name already exists.') : 'Unable to save.'); } finally { setBusy(false); }
  }
  async function reconcile() {
    if (!family || !reconcileAccountId || busy) return; setBusy(true); setError('');
    try { if (!isLocalDate(checkedDate)) throw new Error('Enter a valid checked date.'); await rpc('reconcile_account', { p_family_id: family.id, p_account_id: reconcileAccountId, p_actual_balance_minor: parseMoney(actualBalance, true), p_checked_date: checkedDate, p_idempotency_key: Crypto.randomUUID() }); setReconcileAccountId(null); setActualBalance(''); await refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to reconcile account.'); } finally { setBusy(false); }
  }
  async function setArchived(account: Account, archivedState: boolean) {
    if (!family || busy) return; setBusy(true); setError('');
    try { await rpc('archive_account', { p_family_id: family.id, p_account_id: account.id, p_archived: archivedState, p_idempotency_key: Crypto.randomUUID() }); await refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message.replace('FINAL_ACTIVE_ACCOUNT', 'Create another active account before archiving the final account.').replace('ACCOUNT_ALREADY_EXISTS', 'An active account with this name already exists. Rename it before restoring this account.') : `Unable to ${archivedState ? 'archive' : 'restore'} account.`); } finally { setBusy(false); }
  }
  async function saveAccountEdit() {
    if (!family || !editingAccountId || busy) return; setBusy(true); setError('');
    try { if (!editingName.trim() || !/^\d+$/.test(editingSortOrder)) throw new Error('Enter an account name and non-negative display order.'); await rpc('update_account_extended', { p_family_id: family.id, p_account_id: editingAccountId, p_name: editingName.trim(), p_account_type: editingType, p_institution: editingInstitution, p_sort_order: Number(editingSortOrder), p_display_credit_as_positive: editingCreditPositive, p_idempotency_key: Crypto.randomUUID() }); setEditingAccountId(null); setEditingName(''); await refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message.replace('ACCOUNT_ALREADY_EXISTS', 'An account with this name already exists.') : 'Unable to update account.'); } finally { setBusy(false); }
  }
  async function saveTransfer() {
    if (!family || busy) return; setBusy(true); setError('');
    try { if (!transferFrom || !transferTo || transferFrom === transferTo) throw new Error('Choose two different accounts.'); if (!isLocalDate(transferDate)) throw new Error('Enter a valid transfer date.'); await rpc('create_account_transfer', { p_family_id: family.id, p_from_account_id: transferFrom, p_to_account_id: transferTo, p_local_date: transferDate, p_amount_minor: parseMoney(transferAmount), p_description: transferDescription, p_remarks: transferRemarks, p_idempotency_key: Crypto.randomUUID() }); setTransferOpen(false); setTransferAmount(''); setTransferRemarks(''); await refresh(); await Promise.all([client.invalidateQueries({ queryKey: ['activity', family.id] }), client.invalidateQueries({ queryKey: ['report', family.id] })]); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to transfer money.'); } finally { setBusy(false); }
  }

  return <Screen title="Accounts" subtitle={family?.name}>
    <QueryFeedback pending={query.isPending} error={query.error} retry={query.refetch} />{error && <Notice tone="danger" message={error} />}
    <Card><AppText variant="heading">Accounts dashboard</AppText><AppText variant="amount">Current balance {formatMoney(sum(active, 'balance_minor'), family?.currency_code, family?.currency_symbol)}</AppText><View style={{ gap: 6, marginTop: 8 }}><AppText>Beginning balance: {formatMoney(sum(active, 'beginning_balance_minor'), family?.currency_code, family?.currency_symbol)}</AppText><AppText>Total deposits: {formatMoney(sum(active, 'total_deposits_minor'), family?.currency_code, family?.currency_symbol)}</AppText><AppText>Total withdrawals: {formatMoney(sum(active, 'total_withdrawals_minor'), family?.currency_code, family?.currency_symbol)}</AppText><AppText>Balance adjustments: {formatMoney(sum(active, 'total_adjustments_minor'), family?.currency_code, family?.currency_symbol)}</AppText></View></Card>
    {family?.role !== 'VIEWER' && active.length >= 2 && <Card tone="accent"><AppText variant="heading">Move money between accounts</AppText><AppText muted>A transfer creates two linked balance adjustments atomically, so account totals always stay consistent.</AppText><AppButton label={transferOpen ? 'Close transfer' : 'New account transfer'} kind="secondary" onPress={() => setTransferOpen(!transferOpen)} />{transferOpen && <><Choice label="From account" value={transferFrom} options={active.map((account) => ({ value: account.id, label: account.name }))} onChange={setTransferFrom} /><Choice label="To account" value={transferTo} options={active.map((account) => ({ value: account.id, label: account.name }))} onChange={setTransferTo} /><AppField label="Amount" value={transferAmount} onChangeText={setTransferAmount} keyboardType="decimal-pad" /><AppField label="Transfer date (YYYY-MM-DD)" value={transferDate} onChangeText={setTransferDate} /><AppField label="Description" value={transferDescription} onChangeText={setTransferDescription} maxLength={240} /><AppField label="Remarks" value={transferRemarks} onChangeText={setTransferRemarks} multiline maxLength={2000} /><AppButton label="Transfer money" loading={busy} onPress={() => { void saveTransfer(); }} /></>}</Card>}
    <AppText variant="heading">Active accounts</AppText>
    {active.map((account) => { const status = checkedStatus(account, today); const difference = account.actual_balance_minor === null || account.actual_balance_minor === undefined ? null : (BigInt(account.actual_balance_minor) - BigInt(account.balance_minor)).toString(); return <Card key={account.id}><AppText variant="heading">{account.name}</AppText><AppText variant="amount">{formatMoney(account.display_credit_as_positive ? (-BigInt(account.balance_minor)).toString() : account.balance_minor, family?.currency_code, family?.currency_symbol)}</AppText><AppText muted>{account.account_type.replaceAll('_', ' ')}{account.institution ? ` · ${account.institution}` : ''} · Opened {account.opening_date}</AppText><AppText muted>Beginning {formatMoney(account.beginning_balance_minor, family?.currency_code, family?.currency_symbol)} · Deposits {formatMoney(account.total_deposits_minor ?? '0', family?.currency_code, family?.currency_symbol)} · Withdrawals {formatMoney(account.total_withdrawals_minor ?? '0', family?.currency_code, family?.currency_symbol)} · Adjustments {formatMoney(account.total_adjustments_minor ?? '0', family?.currency_code, family?.currency_symbol)}</AppText><AppText>Reconciliation: {status}</AppText>{account.last_checked_date && <AppText muted>Last checked {account.last_checked_date}</AppText>}{difference !== null && <AppText>Actual {formatMoney(account.actual_balance_minor!, family?.currency_code, family?.currency_symbol)} · Difference {formatMoney(difference, family?.currency_code, family?.currency_symbol)}</AppText>}
      {editingAccountId === account.id ? <><AppField label="Account name" value={editingName} onChangeText={setEditingName} maxLength={80} /><Choice label="Account type" value={editingType} onChange={setEditingType} options={accountTypes.map((value) => ({ value, label: value.replaceAll('_', ' ') }))} /><AppField label="Institution (optional)" value={editingInstitution} onChangeText={setEditingInstitution} maxLength={120} /><AppField label="Display order" value={editingSortOrder} onChangeText={setEditingSortOrder} keyboardType="number-pad" /><Choice label="Credit/debt display" value={editingCreditPositive ? 'POSITIVE' : 'SIGNED'} options={[{ value: 'SIGNED', label: 'Show stored sign' }, { value: 'POSITIVE', label: 'Show debt as positive' }]} onChange={(value) => setEditingCreditPositive(value === 'POSITIVE')} /><AppButton label="Save account changes" loading={busy} onPress={() => { void saveAccountEdit(); }} /><AppButton label="Cancel editing" kind="secondary" disabled={busy} onPress={() => { setEditingAccountId(null); setEditingName(''); }} /></> : canManage && <AppButton label="Edit account" kind="secondary" disabled={busy} onPress={() => { setEditingAccountId(account.id); setEditingName(account.name); setEditingType(account.account_type); setEditingInstitution(account.institution ?? ''); setEditingSortOrder(String(account.sort_order ?? 0)); setEditingCreditPositive(account.display_credit_as_positive ?? false); }} />}
      {family?.role !== 'VIEWER' && <AppButton label={reconcileAccountId === account.id ? 'Cancel reconciliation' : 'Reconcile actual balance'} kind="secondary" onPress={() => { setReconcileAccountId(reconcileAccountId === account.id ? null : account.id); setActualBalance(account.actual_balance_minor === null || account.actual_balance_minor === undefined ? '' : decimalMoney(account.actual_balance_minor)); }} />}
      <AppButton label="View account ledger" kind="secondary" onPress={() => router.push({ pathname: '/accounts/[id]', params: { id: account.id } })} />
      {canManage && <AppButton label="Archive account" kind="destructive" disabled={busy} onPress={() => Alert.alert('Archive account?', `${BigInt(account.balance_minor) === 0n ? '' : `This account currently has ${formatMoney(account.balance_minor, family?.currency_code, family?.currency_symbol)}. `}Past transactions remain, but new transactions cannot use it.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', style: 'destructive', onPress: () => { void setArchived(account, true); } }])} />}
      {reconcileAccountId === account.id && <><AppField label="Actual balance (negative for debt)" value={actualBalance} onChangeText={setActualBalance} keyboardType="numbers-and-punctuation" /><AppField label="Checked date (YYYY-MM-DD)" value={checkedDate} onChangeText={setCheckedDate} /><AppButton label="Save reconciliation" loading={busy} onPress={() => { void reconcile(); }} /></>}
    </Card>; })}
    {active.length === 0 && <Notice message="Create your first cash, bank or wallet account before adding transactions." />}
    {canManage && <><AppText variant="heading">Archived accounts</AppText>{archived.map((account) => <Card key={account.id}><AppText variant="heading">{account.name}</AppText><AppText muted>{account.account_type.replaceAll('_', ' ')} · Archived {new Date(account.archived_at!).toLocaleDateString()}</AppText><AppText>Historical balance: {formatMoney(account.balance_minor, family?.currency_code, family?.currency_symbol)}</AppText><AppButton label="Restore account" loading={busy} onPress={() => { void setArchived(account, false); }} /></Card>)}{archived.length === 0 && <AppText muted>No archived accounts.</AppText>}</>}
    {canManage && <Card><AppText variant="heading">Add account</AppText><AppField label="Account name" value={name} onChangeText={(value) => { setName(value); setKey(Crypto.randomUUID()); }} maxLength={80} /><Choice label="Account type" value={type} onChange={(value) => { setType(value); setKey(Crypto.randomUUID()); }} options={accountTypes.map((value) => ({ value, label: value.replaceAll('_', ' ') }))} /><AppField label="Institution (optional)" value={institution} onChangeText={(value) => { setInstitution(value); setKey(Crypto.randomUUID()); }} maxLength={120} /><AppField label="Display order" value={sortOrder} onChangeText={(value) => { setSortOrder(value); setKey(Crypto.randomUUID()); }} keyboardType="number-pad" /><Choice label="Credit/debt display" value={creditPositive ? 'POSITIVE' : 'SIGNED'} options={[{ value: 'SIGNED', label: 'Show stored sign' }, { value: 'POSITIVE', label: 'Show debt as positive' }]} onChange={(value) => { setCreditPositive(value === 'POSITIVE'); setKey(Crypto.randomUUID()); }} /><AppField label="Opening date (YYYY-MM-DD)" value={date} onChangeText={(value) => { setDate(value); setKey(Crypto.randomUUID()); }} /><AppField label="Beginning balance (negative for debt)" value={balance} onChangeText={(value) => { setBalance(value); setKey(Crypto.randomUUID()); }} keyboardType="numbers-and-punctuation" /><AppButton label="Save account" loading={busy} onPress={() => { void save(); }} /></Card>}
    <AppButton label="Back" kind="secondary" onPress={() => router.back()} />
  </Screen>;
}
