import { useState, useRef } from 'react';
import * as Crypto from 'expo-crypto';
import { router } from 'expo-router';
import { useQueryClient } from '@tanstack/react-query';
import { createFamilySchema } from '@family-ledger/contracts';
import { suggestedCurrencySymbol } from '@family-ledger/domain';
import { Screen } from '@/components/ui/screen'; import { AppField } from '@/components/ui/app-field'; import { AppButton } from '@/components/ui/app-button'; import { Notice } from '@/components/ui/notice'; import { Card } from '@/components/ui/card'; import { AppText } from '@/components/ui/app-text'; import { createDemoFamily, createFamily } from '@/infrastructure/supabase/families'; import { useAuth } from '@/providers/auth-provider';

export default function CreateFamilyScreen() {
  const { user } = useAuth(); const queryClient = useQueryClient(); const [name, setName] = useState(''); const [currency, setCurrency] = useState('INR'); const [currencySymbol, setCurrencySymbol] = useState('₹'); const [timezone, setTimezone] = useState('Asia/Kolkata'); const request = useRef<{ signature: string; key: string } | null>(null); const demoRequest = useRef(Crypto.randomUUID()); const [startMonth, setStartMonth] = useState('1'); const [year, setYear] = useState(String(new Date().getFullYear())); const [loading, setLoading] = useState(false); const [demoLoading, setDemoLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit() { if (loading) return; const signature = JSON.stringify([name,currency,currencySymbol,timezone,startMonth,year]); const idempotencyKey = request.current?.signature === signature ? request.current.key : Crypto.randomUUID(); request.current = { signature, key: idempotencyKey }; const parsed = createFamilySchema.safeParse({ name, currencyCode: currency, currencySymbol, timezone, fiscalStartMonth: Number(startMonth), reportingStartYear: Number(year), idempotencyKey }); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? 'Check the form.'); return; } setLoading(true); setError(null); try { await createFamily(parsed.data); await queryClient.invalidateQueries({ queryKey: ['families', user?.id] }); router.replace('/'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create family.'); } finally { setLoading(false); } }
  async function createSample() { if (demoLoading) return; setDemoLoading(true); setError(null); try { await createDemoFamily(demoRequest.current); await queryClient.invalidateQueries({ queryKey: ['families', user?.id] }); router.replace('/'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create the sample family.'); } finally { setDemoLoading(false); } }
  return <Screen title="Create your family" subtitle="You become the Owner and approve everyone who joins.">{error && <Notice tone="danger" message={error} />}<Card><AppField label="Family name" value={name} onChangeText={setName} placeholder="Sharma family" /><AppField label="Reporting start month (1–12)" value={startMonth} onChangeText={setStartMonth} keyboardType="number-pad" /><AppField label="Reporting start year" value={year} onChangeText={setYear} keyboardType="number-pad" /><AppField label="Currency (three-letter code)" value={currency} onChangeText={(value) => { const code = value.toUpperCase(); setCurrency(code); if (code.length === 3) setCurrencySymbol(suggestedCurrencySymbol(code)); }} maxLength={3} autoCapitalize="characters" /><AppField label="Currency symbol" value={currencySymbol} onChangeText={setCurrencySymbol} maxLength={8} /><AppField label="Timezone" value={timezone} onChangeText={setTimezone} autoCapitalize="none" /><AppButton label="Create family" onPress={submit} loading={loading} disabled={demoLoading} /></Card><Card tone="accent"><AppText variant="eyebrow">Explore first</AppText><AppText variant="heading">See a complete sample ledger</AppText><AppText muted>Create a private sample family with two accounts, common categories and this month’s transactions. You can edit or leave it at any time.</AppText><AppButton label="Create sample family" kind="secondary" onPress={() => { void createSample(); }} loading={demoLoading} disabled={loading} /></Card><AppText muted>Have an invitation? Open its link or use Accept invite after signing in.</AppText><AppButton label="Accept an invitation" kind="secondary" onPress={() => router.push('/(onboarding)/accept-invite')} /></Screen>;
}
